source "https://rubygems.org"

gem "jekyll", "~> 3.8.3"
gem "jekyll-assets"
gem "jekyll-seo-tag"

gem 'bootstrap', '~> 4.1.1'

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
# gem "github-pages", group: :jekyll_plugins

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
